export const recommendedsList = [
  {
    id: "1",
    hotelImage: require("../assets/images/room/room_1.jpg"),
    hotelName: "Novotel зочид буудал хурлын том өрөө",
    rating: 5.0,
    place: "Сүхбаатарын талбай",
    amount: 70,
  },
  {
    id: "2",
    hotelImage: require("../assets/images/room/room_2.jpg"),
    hotelName: "Shangrilla center хурлын том өрөө",
    rating: 4.0,
    place: "Сүхбаатарын талбай",
    amount: 100,
  },
  {
    id: "3",
    hotelImage: require("../assets/images/room/room_3.jpg"),
    hotelName: "Blue Sky tower хурлын заал",
    rating: 5.0,
    place: "Сүхбаатарын талбай",
    amount: 90,
  },
  {
    id: "4",
    hotelImage: require("../assets/images/room/room_4.jpg"),
    hotelName: "Central tower оффис өрөө",
    rating: 4.0,
    place: "Сүхбаатарын талбай",
    amount: 50,
  },
  {
    id: "5",
    hotelImage: require("../assets/images/room/room_5.jpg"),
    hotelName: "Encanto tower оффис өрөө",
    rating: 3.0,
    place: "Хан-Уул",
    amount: 40,
  },
  {
    id: "6",
    hotelImage: require("../assets/images/room/room_6.jpg"),
    hotelName: "Sempinski hotel restaurant",
    rating: 5.0,
    place: "13-р хороолол",
    amount: 180,
  },
];
